### ISSUE TITLE
Anaconda packaging

### ISSUE THREAD

**Issue by frol** [cenkalti/kuyruk#44]
Hi @cenkalti,

I have prepared a [Kuyruk package](https://github.com/conda-forge/staged-recipes/pull/1794) for [Anaconda Python](https://www.continuum.io/anaconda-overview) ([Conda-Forge repository](https://conda-forge.github.io/)). Would you like to be listed as the package maintainer?

**Comment by cenkalti** [comment]
Yes, thank you.
