### ISSUE TITLE
Tune performance

### ISSUE THREAD

**Issue by frol** [cenkalti/kuyruk#53]
I am very interested in getting maximum available performance out of RabbitMQ as I have a need to schedule a heap of tasks (I want to handle 100k tasks in a reasonable time, a few minutes). Given my old experiments reported in #51 (238 tasks/second), it will take ~400 seconds (~7 minutes) to schedule 100k tasks.

I think the current bottleneck is in `amqp` library, and it seems that [`rabbitmq`](https://github.com/jbg/rabbitmq/blob/master/example.py) will work better as it implemented CFFI bindings to librabbitmq native library.

This issue is just a placeholder for the related experiments, yet if it is doable, it is better to optimize it sooner rather later.

**Comment by frol** [comment]
@cenkalti I would love to hear any comment from you on the matter. I might dig into the performance tuning myself next month, so I would love to have any valuable information on hands like whether you see any complexity of switching `amqp` to `rabbitmq` module right away given that the interfaces should be quite similar since they are just drivers to the same RabbitMQ server.

**Comment by cenkalti** [comment]
Hi @frol. Sorry about the delayed answer. We didn't design Kuyruk for high performance scenarios and I don't want to give up the beauty of the pure-Python library by replacing it with `rabbitmq` package that uses CFFI bindings. I would like to close this issue if it is okay for you.

**Comment by frol** [comment]
@cenkalti I see. Well, I like Kuyruk API, so I will tune its performance rather than switch to anything else. If I manage to get a better performance without sacrificing the beauty, I will make a PR.
