### ISSUE TITLE
Check if a worker already launched

### ISSUE THREAD

**Issue by nathan30** [cenkalti/kuyruk#60]
Hi,

First, thanks for your work ! 
I used it with success in my Python project but I'm facing a problem. I need to have a control of the worker (See if one worker is already launched for exemple, to avoid launch two worker). Is there any possibilities to do that ?

**Comment by cenkalti** [comment]
Kuyruk has no such feature. You can use a wrapper shell script that check running processes before starting a worker but I don't recommend it. I would use a proper process manager such as systemd.
