### ISSUE TITLE
Werkzeug package issue when running worker

### ISSUE THREAD

**Issue by nathan30** [cenkalti/kuyruk#61]
Hi,

I have the following error when I'm running `/usr/local/bin/kuyruk --app src.main.OCforMaarch worker`

> Traceback (most recent call last):
>   File "/usr/local/bin/kuyruk", line 6, in <module>
>     from kuyruk.__main__ import main
>   File "/usr/local/lib/python3.7/dist-packages/kuyruk/__init__.py", line 4, in <module>
>     from kuyruk.kuyruk import Kuyruk
>   File "/usr/local/lib/python3.7/dist-packages/kuyruk/kuyruk.py", line 10, in <module>
>     from kuyruk.config import Config
>   File "/usr/local/lib/python3.7/dist-packages/kuyruk/config.py", line 126, in <module>
>     for k, v in entry_point.load().items():
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2410, in load
>     self.require(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2433, in require
>     items = working_set.resolve(reqs, env, installer, extras=self.extras)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'Werkzeug>=0.14' distribution was not found and is required by Flask

I'm running Ubuntu 19.04

When I do pip3 freeze I see for Werkzeug and kuyruk : 

> Kuyruk==9.1.0
> Kuyruk-Manager==1.5.2
> Werkzeug==0.15.2

**Comment by cenkalti** [comment]
Looks like `werkzeug` package is not installed correctly. Can you try reinstalling it?

**Comment by nathan30** [comment]
> werkzeug

Just try `pip3 uninstall werkzeug` and then `pip3 install -U werkzeug` and same issue :/ 

I didn't have any errors while installing the `werkzeug` package

**Comment by cenkalti** [comment]
Are you using any virtualenv? If not, then probably there is an issue with your local install. Can you try creating an isolated virtualenv and installing in there?

**Comment by nathan30** [comment]
> Are you using any virtualenv? If not, then probably there is an issue with your local install. Can you try creating an isolated virtualenv and installing in there?

Just try with pipenv : 
`sudo pip3 install pipenv
pipenv shell
pipenv install kuyruk
pipenv install flash
pipenv install Werkzeug
pipenv run /usr/local/bin/kuyruk --app src.main.OCforMaarch worker`

Same issue :/

**Comment by cenkalti** [comment]
I have run it successfully with pipenv and without pipenv. It must be problem with your setup. Try running this Dockerfile: https://gist.github.com/cenkalti/df9432fc35c0931a3e330ee79d834223
