### ISSUE TITLE
SSL/TLS support 

### ISSUE THREAD

**Issue by kangelos** [cenkalti/kuyruk#65]
Hi Cenk , thanks for a great little project. Would you please also enable ssl on the AMQP connections ? it literally a 2 line change 
RABBIT_SSL = TRUE in config

ssl=self.config.RABBIT_SSL in amqp.connection.

Best Regards

**Comment by cenkalti** [comment]
Hi @kangelos,

I have released a new version including the change.

https://pypi.org/project/Kuyruk/9.3.0/

**Comment by kangelos** [comment]
Sorry for the delayed answer, good job!
I have some code to make your decorator conditional so you can Import a jobs def python library and call it from any other python script! If you are interested let me know

**Comment by kangelos** [comment]
https://github.com/kangelos/devops_tools/blob/master/taskify.py
