### ISSUE TITLE
Kuyruk inactive after python sys.exit

### ISSUE THREAD

**Issue by nathan30** [cenkalti/kuyruk#66]
Hi,

In my python program I have a sys.exit() in some case. When the sys.exit() is reached, my service (who runs kuyruk) became inactive. Is it normal ? Is there any way to keep the service active but exit the python script ?

**Comment by cenkalti** [comment]
I don't know how is your service running but you can call `os._exit()` from your script to exit immediately.

**Comment by nathan30** [comment]
> I don't know how is your service running but you can call `os._exit()` from your script to exit immediately.

It will not disable the kuyruk service ?

**Comment by cenkalti** [comment]
What do you mean by "kuyruk service"? Is it the worker or the service that is queuing tasks?
