### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by nathan30** [cenkalti/kuyruk#72]
Hi,

Some users of my project (https://github.com/edissyum/opencaptureforinvoices/) have the following error while runing kuyruk :+1: 

`opt/OpenCaptureForInvoices/bin/scripts/service_workerOC.sh : ligne 24 : 23377 Instruction non permise (core dumped) /usr/local/bin/kuyruk --app bin.src.main.OCforInvoices_worker worker --queue invoices`

This error happen just by starting the worker.. Any ideas ?

Thanks in advance

**Comment by cenkalti** [comment]
It may happen if you have upgraded Python after installing dependencies. Try to create a new Python environment and install requirements from scratch.
