### ISSUE TITLE
Kuyruk queue with variable name

### ISSUE THREAD

**Issue by nathan30** [cenkalti/kuyruk#76]
Hi,

I'm currently making a web app that can load different configuration based on the URL. I wonder if I can use Kuyruk to specify a queue for each instance. 

For exemple for this URL : http://localhost/edissyum/dist/ --> each process I want to queue will use the task with queue id `edissyum`

The problem is, it could be `edissyum` or something else, it has to be dynamic, is there any solution I can imagine with Kuyruk ? Like declare my decorator and then change the queue name maybe ?

Thanks in advance

**Comment by cenkalti** [comment]
It is possible if you use [send_to_queue](https://kuyruk.readthedocs.io/en/latest/api.html#kuyruk.Task.send_to_queue) method when sending tasks. It has `host` kwarg that gets appended to the queue name. This feature was designed to send the tasks that targeted for specific hosts (separate workers would be run on different queues on each host) but you can also use it to separate the work for each process.
